# Generated by Django 3.2.5 on 2022-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('date_of_news', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'news_list',
            },
        ),
    ]
